name: test

on:
  push:
  pull_request:
  schedule:
    - cron: '25 10 * * *'

jobs:
  test:
    if: ${{ startsWith(github.repository, 'ruby/') || github.event_name != 'schedule' }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 'head', '3.0', '2.7', '2.6' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - ruby: jruby-head
          - ruby: jruby-9.3
          - ruby: truffleruby
          - ruby: truffleruby-head
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}
    steps:
    - name: git config
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
        git config --global advice.detachedHead 0
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Experiment with a manual bundle install
      run: bundle install
    - name: Run test
      run: rake # Attempting without 'bundle exec'
    - id: build
      run: |
        rake build
        echo "::set-output name=pkg::${GITHUB_REPOSITORY#*/}-${RUNNING_OS%-*}"
      env:
        RUNNING_OS: ${{matrix.os}}
      if: "matrix.ruby == '3.0'"
      shell: bash
    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        path: pkg/*.gem
        name: ${{steps.build.outputs.pkg}}
      if: steps.build.outputs.pkg
